spring:
  datasource:
    url: jdbc:mysql://210.183.11.113:3306/addiction?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Navskd1048!
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:postgresql://${DB_ENDPOINT}:5432/postgres?useSSL=false&serverTimezone=Asia/Seoul
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    #    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          exception-handling: ignore
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: mongodb+srv://addiction1215:4LLbTwmmDUQflGb1@cluster0.jcjrpc1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: addiction
    #spring:
    #  datasource:
    #    url: jdbc:mysql://${DB_ENDPOINT}:3306/addiction?useSSL=false&serverTimezone=Asia/Seoul
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #  jpa:
    #    hibernate:
    #      ddl-auto: update
    #    open-in-view: false
    #    properties:
    #      hibernate:
    #        default_batch_fetch_size: 100
    #        jdbc:
    #          exception-handling: ignore

    logging:
      level:
        p6spy: info

      decorator:
        datasource:
          p6spy:
            enable-logging: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: addiction1215@gmail.com
    password: cbhavuvuyntkgskr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

oauth:
  kakao:
    api:
      url: https://kapi.kakao.com
      name: kakaoApi
  google:
    api:
      url: https://www.googleapis.com
      name: googleApi
  naver:
    api:
      url: https://openai.naver.com
      name: naverApi

jwt:
  secret-key: vY3ZvAT2GZwhPWy/ywl3xl3Nd/RYJwLQ+C/CQ9H2K4u2QGlS9Qk5MwKgJEQwT4BIlQxGmR8wdb6AlJRTYkokjQ==

aes:
  key-value: 2e3d9df0ada72f9e378b8494fce2923826cb1af222ab3462cb506a921813ccf7

logging:
  config: classpath:logback/logback-config.xml

oracle:
  cloud:
    region: ap-chuncheon-1
  name-space-name: axw0f9kcetpw
  user:
    bucket-name: user-profile-dev
  challenge:
    bucket-name: challenge-dev