name: ğŸš€ ë°°í¬

on:
  pull_request:
    types: [ closed ]
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
    steps:
      - name: ğŸ”¨ JDK 17 ì„¸íŒ…
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ” í˜„ì¬ ë””ë ‰í† ë¦¬ ë³´ê¸°
        run: ls -al

      - name: ğŸ”¨ gradlew ì‹¤í–‰ ê¶Œí•œ ì„¤ì •
        run: chmod +x gradlew

      - name: ğŸ”¨ Gradle ìºì‹œ ì„¤ì •
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: ğŸ”¨ ë¹„ë°€ ì„¤ì • íŒŒì¼ ë³µì‚¬
        run: ./gradlew copySecret

      - name: ğŸ”¨ Gradle ë¹Œë“œ
        run: ./gradlew build --parallel

      - name: ğŸ“¦ jar, appspec, ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ ë³µì‚¬
        run: |
          mkdir -p before-deploy
          cp ./build/libs/*.jar ./before-deploy/
          cp ./appspec.yml ./before-deploy/
          cp -r ./scripts/dev/ ./before-deploy/scripts/

      - name: ğŸ—œï¸ ë°°í¬ íŒ¨í‚¤ì§€ ìƒì„±
        run: zip -r -qq ./deploy.zip ./before-deploy/

      - name: ğŸ”‘ SSH í‚¤ ì„¤ì •
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

      - name: ğŸ”‘ Lightsail í˜¸ìŠ¤íŠ¸ ì¶”ê°€
        run: |
          ssh-keyscan -H ${{ secrets.DEV_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: ğŸš€  ì„œë²„ì— íŒŒì¼ ì—…ë¡œë“œ
        run: |
          scp ./deploy.zip ubuntu@${{ secrets.DEV_SERVER_IP }}:/home/ubuntu/deploy.zip
          ssh ubuntu@${{ secrets.DEV_SERVER_IP }} "
            unzip -o /home/ubuntu/deploy.zip -d /home/ubuntu &&
            rm -rf /home/ubuntu/app/* &&
            mv /home/ubuntu/before-deploy/* /home/ubuntu/app/ &&
            chmod +x /home/ubuntu/app/scripts/*.sh"

      - name: ğŸ¯ Ubuntu ì„œë²„ì—ì„œ ë°°í¬ ì‹¤í–‰
        run: |
          ssh ubuntu@${{ secrets.LIGHTSAIL_HOST }} "/home/ubuntu/app/scripts/run_new_was.sh"

      - name: ğŸ§¹ ì„ì‹œ íŒŒì¼ ì •ë¦¬
        run: |
          ssh ubuntu@${{ secrets.LIGHTSAIL_HOST }} "
            rm -rf /home/ubuntu/deploy.zip /home/ubuntu/before-deploy"
