name: ğŸš€ ìš´ì˜ ë°°í¬

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd  # dev í™˜ê²½ secrets ì‚¬ìš©
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      USER_BUCKET: ${{ secrets.USER_BUCKET }}
      CHALLENGE_BUCKET: ${{ secrets.CHALLENGE_BUCKET }}
      CHALLENGE_BADGE_BUCKET: ${{ secrets.CHALLENGE_BADGE_BUCKET }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: ğŸ”¨ JDK 17 ì„¸íŒ…
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ”¨ gradlew ì‹¤í–‰ ê¶Œí•œ ì„¤ì •
        run: chmod +x gradlew

      - name: ğŸ”¨ Gradle ìºì‹œ ì„¤ì •
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: ğŸ”‘ SSH í‚¤ ì„¤ì •
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: ğŸ”‘ Ubuntu í˜¸ìŠ¤íŠ¸ ì¶”ê°€
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: ğŸ”¥ FCM ì„¤ì • íŒŒì¼ ê°€ì ¸ì˜¤ê¸°
        run: |
          mkdir -p src/main/resources
          scp ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/fcm/addiction-firebase.json ./src/main/resources/addiction-firebase.json

      - name: ğŸ”¨ Gradle ë¹Œë“œ
        run: ./gradlew build --parallel

      - name: ğŸ“¦ jar, appspec, ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ ë³µì‚¬
        run: |
          mkdir -p before-deploy
          cp ./build/libs/*.jar ./before-deploy/
          cp ./appspec.yml ./before-deploy/
          cp -r ./scripts/prd/ ./before-deploy/scripts/

      - name: ğŸ—œï¸ ë°°í¬ íŒ¨í‚¤ì§€ ìƒì„±
        run: zip -r -qq ./deploy.zip ./before-deploy/

      - name: ğŸš€ ì„œë²„ì— íŒŒì¼ ì—…ë¡œë“œ
        run: |
          scp ./deploy.zip ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/deploy.zip
          ssh ubuntu@${{ secrets.SERVER_IP }} "
            unzip -o /home/ubuntu/deploy.zip -d /home/ubuntu &&
            rm -rf /home/ubuntu/app/* &&
            mv /home/ubuntu/before-deploy/* /home/ubuntu/app/ &&
            chmod +x /home/ubuntu/app/scripts/*.sh"

      - name: ğŸ¯ Ubuntu ì„œë²„ì—ì„œ ë°°í¬ ì‹¤í–‰
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} "/home/ubuntu/app/scripts/run_new_was.sh"

      - name: ğŸ¯ Ubuntu ì„œë²„ì—ì„œ Health Checking
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} "/home/ubuntu/app/scripts/health.sh"

      - name: ğŸ¯ Ubuntu ì„œë²„ì—ì„œ Blue/Green Switching
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} "/home/ubuntu/app/scripts/switch.sh"

      - name: ğŸ§¹ ì„ì‹œ íŒŒì¼ ì •ë¦¬
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} "
            rm -rf /home/ubuntu/deploy.zip /home/ubuntu/before-deploy"
